name: Scrape AniWatch Data

on:
  push:
    branches:
      - main
  schedule:
    # Jalankan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch: # Izinkan pemicuan manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # TAMBAHKAN BLOK INI UNTUK MEMBERI IZIN
    permissions:
      contents: write # Beri izin untuk menulis (commit & push) ke repositori

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add anime_data.json
          # Lakukan commit hanya jika ada perubahan pada file
          git diff --staged --quiet || (git commit -m "Update anime data" && git push)
